ABSTRACT_ATTR = '__abstract__'
NO_ROUTE_ATTR = '__fcb_no_route__'
NO_ROUTES_ATTR = '__fcb_no_route_method_names__'
REMOVE_SUFFIXES_ATTR = '__fcb_remove_suffixes__'
ROUTE_ATTR = '__fcb_route__'
ROUTES_ATTR = '__fcb_routes__'
